### ISSUE TITLE
Organisation Settings not saved

### ISSUE THREAD

**Issue by julienmarie** [thejoshsmith/commerce-xero#5]
Once connected to Xero, the Organisation page was blank.
I noticed in the db that the entry in xero_connections was set to FALSE for selected and enabled fields
I put them to TRUE and now settings are being displayed.
After selecting the right accounts and saving, items are not being saved ( but success message appears ).

By the way, I'm running PostgresQL.

**Comment by moacode** [comment]
Thanks @julienmarie, that sounds odd. I'll run a quick test with PostgreSQL.

**Comment by moacode** [comment]
@julienmarie I have confirmed this as a bug with PostgreSQL. Will look at resolving it now.

**Comment by moacode** [comment]
@julienmarie this is resolved in [release 1.0.3](https://github.com/thejoshsmith/commerce-xero/releases/tag/1.0.3) 😄
